---

- name: Ensure dotfiles repository is cloned locally.
  copy:
    src: "files/dotfiles/{{ item }}"
    dest: "{{ dotfiles_home }}/{{ item }}"
    group: staff
    mode: 0770
  with_items: "{{dotfiles_files}}"
  failed_when: false
  sudo: no
