---
- name: Setup homebrew install path.
  file:
    path: "{{ homebrew_install_path }}"
    group: admin
    mode: 0775
    state: directory
    recurse: true
  sudo: yes

- name: Check if homebrew binary is already in place.
  stat: "path={{ homebrew_brew_bin_path }}/brew"
  register: homebrew_binary

- name: Ensure homebrew is installed.
  shell: creates={{ homebrew_brew_bin_path }}/brew curl -fsSL https://github.com/Homebrew/homebrew/tarball/master | tar xz --strip 1 -C {{ homebrew_install_path }}
  when: homebrew_binary.stat.exists == false or homebrew_force_install == true
  sudo: yes

- name: Ensure proper permissions on homebrew_install_path dirs.
  file:
    path: "{{ homebrew_install_path }}"
    group: admin
    mode: 0775
    state: directory
    recurse: true
  sudo: yes
  when: homebrew_binary.stat.exists == false or homebrew_force_install == true

- name: Check if homebrew binary is already in place.
  stat: "path={{ homebrew_brew_bin_path }}/brew"
  register: homebrew_binary

- name: Symlink brew to homebrew_brew_bin_path.
  file:
    src: "{{ homebrew_install_path }}/bin/brew"
    dest: "{{ homebrew_brew_bin_path }}/brew"
    state: link
  when: homebrew_binary.stat.exists == false or homebrew_force_install == true
  sudo: yes

- name: Run cask cleanup
  raw: "brew update && brew cleanup && brew cask cleanup && brew uninstall --force brew-cask && brew update"
  when: homebrew_cask_cleanup == true

#- name: Upgrade homebrew
#  command: brew upgrade

- name: Update homebrew
  command: brew update
  when: homebrew_binary.stat.exists == false or homebrew_force_install == true or homebrew_force_update == true

- name: Upgrade all homebrew packages (if configured).
  homebrew: update_homebrew=yes upgrade_all=yes
  when: homebrew_upgrade_all_packages

- name: Ensure base taps are tapped.
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{base_homebrew_taps}}"

- name: Ensure configured taps are tapped.
  homebrew_tap: tap={{ item }} state=present
  with_items: "{{homebrew_taps}}"

- name: Ensure configured homebrew packages are installed.
  homebrew: name={{ item }} state=present
  with_items: "{{homebrew_packages}}"

- name: Install configured cask applications
  homebrew_cask: name={{ item }} state=present
  environment:
    HOMEBREW_CASK_OPTS: "--appdir={{ homebrew_cask_appdir }}"
  with_items: "{{homebrew_cask_apps}}"
  #sudo: yes
